[package]
name = "solana-compute-budget"
description = "Solana compute budget"
documentation = "https://docs.rs/solana-compute-budget"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
solana-frozen-abi = { workspace = true, optional = true }
solana-sdk = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[features]
frozen-abi = [
    "dep:solana-frozen-abi",
    "solana-sdk/frozen-abi",
]
