[package]
name = "solana-remote-wallet"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/solana-remote-wallet"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
console = { workspace = true }
dialoguer = { workspace = true }
hidapi = { workspace = true, optional = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
parking_lot = { workspace = true }
qstring = { workspace = true }
semver = { workspace = true }
solana-sdk = { workspace = true }
thiserror = { workspace = true }
uriparse = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }

[features]
default = ["linux-static-hidraw", "hidapi"]
linux-shared-hidraw = ["hidapi/linux-shared-hidraw"]
linux-shared-libusb = ["hidapi/linux-shared-libusb"]
linux-static-hidraw = ["hidapi/linux-static-hidraw"]
linux-static-libusb = ["hidapi/linux-static-libusb"]

[[bin]]
name = "solana-ledger-udev"
path = "src/bin/ledger-udev.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
