[workspace.package]
version = "2.0.3"
description = "Solana SBF test program written in Rust"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
repository = "https://github.com/anza-xyz/agave"
homepage = "https://anza.xyz"
license = "Apache-2.0"
edition = "2021"

[workspace.dependencies]
array-bytes = "=1.4.1"
bincode = { version = "1.1.4", default-features = false }
blake3 = "1.0.0"
byteorder = "1.3.2"
elf = "0.0.10"
getrandom = "0.2.10"
itertools = "0.10.1"
libsecp256k1 = { version = "0.7.0", default-features = false }
log = "0.4.11"
miow = "0.3.6"
net2 = "0.2.37"
num-derive = "0.4.2"
num-traits = "0.2"
rand = "0.8"
rustversion = "1.0.14"
serde = "1.0.112" # must match the serde_derive version, see https://github.com/serde-rs/serde/issues/2584#issuecomment-1685252251
serde_derive = "1.0.112" # must match the serde version, see https://github.com/serde-rs/serde/issues/2584#issuecomment-1685252251
serde_json = "1.0.56"
solana-account-decoder = { path = "../../account-decoder", version = "=2.0.3" }
solana-accounts-db = { path = "../../accounts-db", version = "=2.0.3" }
solana-bpf-loader-program = { path = "../bpf_loader", version = "=2.0.3" }
solana-cli-output = { path = "../../cli-output", version = "=2.0.3" }
solana-compute-budget = { path = "../../compute-budget", version = "=2.0.3" }
solana-curve25519 = { path = "../../curves/curve25519", version = "=2.0.3" }
solana-ledger = { path = "../../ledger", version = "=2.0.3" }
solana-logger = { path = "../../logger", version = "=2.0.3" }
solana-measure = { path = "../../measure", version = "=2.0.3" }
solana-poseidon = { path = "../../poseidon/", version = "=2.0.3" }
solana-program = { path = "../../sdk/program", version = "=2.0.3" }
solana-program-runtime = { path = "../../program-runtime", version = "=2.0.3" }
solana-runtime = { path = "../../runtime", version = "=2.0.3" }
solana-sbf-rust-128bit-dep = { path = "rust/128bit_dep", version = "=2.0.3" }
solana-sbf-rust-invoke-dep = { path = "rust/invoke_dep", version = "=2.0.3" }
solana-sbf-rust-invoked-dep = { path = "rust/invoked_dep", version = "=2.0.3" }
solana-sbf-rust-many-args-dep = { path = "rust/many_args_dep", version = "=2.0.3" }
solana-sbf-rust-mem-dep = { path = "rust/mem_dep", version = "=2.0.3" }
solana-sbf-rust-param-passing-dep = { path = "rust/param_passing_dep", version = "=2.0.3" }
solana-sbf-rust-realloc-dep = { path = "rust/realloc_dep", version = "=2.0.3" }
solana-sbf-rust-realloc-invoke-dep = { path = "rust/realloc_invoke_dep", version = "=2.0.3" }
solana-sdk = { path = "../../sdk", version = "=2.0.3" }
solana-svm = { path = "../../../svm", version = "=2.0.3" }
solana-transaction-status = { path = "../../transaction-status", version = "=2.0.3" }
solana-type-overrides = { path = "../../../type-overrides", version = "=2.0.3" }
agave-validator = { path = "../../validator", version = "=2.0.3" }
solana-zk-token-sdk = { path = "../../zk-token-sdk", version = "=2.0.3" }
solana_rbpf = "=0.8.1"
thiserror = "1.0"

[package]
name = "solana-sbf-programs"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/solana"
readme = "README.md"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[profile.release]
# The test programs are build in release mode
# Minimize their file size so that they fit into the account size limit
strip = true

[features]
sbf_c = []
sbf_rust = []
dummy-for-ci-check = ["sbf_c", "sbf_rust"]

[dev-dependencies]
agave-validator = { workspace = true }
bincode = { workspace = true }
byteorder = { workspace = true }
elf = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
miow = { workspace = true }
net2 = { workspace = true }
solana-account-decoder = { workspace = true }
solana-accounts-db = { workspace = true }
solana-bpf-loader-program = { workspace = true }
solana-cli-output = { workspace = true }
solana-compute-budget = { workspace = true }
solana-ledger = { workspace = true }
solana-logger = { workspace = true }
solana-measure = { workspace = true }
solana-program = { workspace = true }
solana-program-runtime = { workspace = true }
solana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
solana-sbf-rust-invoke-dep = { workspace = true }
solana-sbf-rust-realloc-dep = { workspace = true }
solana-sbf-rust-realloc-invoke-dep = { workspace = true }
solana-sdk = { workspace = true, features = ["dev-context-only-utils"] }
solana-svm = { workspace = true }
solana-transaction-status = { workspace = true }
solana-type-overrides = { workspace = true }
solana_rbpf = { workspace = true }

[[bench]]
name = "bpf_loader"

[workspace]
members = [
    "rust/128bit",
    "rust/128bit_dep",
    "rust/alloc",
    "rust/alt_bn128",
    "rust/alt_bn128_compression",
    "rust/big_mod_exp",
    "rust/call_depth",
    "rust/caller_access",
    "rust/curve25519",
    "rust/custom_heap",
    "rust/dep_crate",
    "rust/deprecated_loader",
    "rust/dup_accounts",
    "rust/error_handling",
    "rust/external_spend",
    "rust/finalize",
    "rust/get_minimum_delegation",
    "rust/inner_instruction_alignment_check",
    "rust/instruction_introspection",
    "rust/invoke",
    "rust/invoke_and_error",
    "rust/invoke_and_ok",
    "rust/invoke_and_return",
    "rust/invoked",
    "rust/iter",
    "rust/log_data",
    "rust/many_args",
    "rust/many_args_dep",
    "rust/mem",
    "rust/mem_dep",
    "rust/membuiltins",
    "rust/noop",
    "rust/panic",
    "rust/param_passing",
    "rust/param_passing_dep",
    "rust/poseidon",
    "rust/rand",
    "rust/realloc",
    "rust/realloc_invoke",
    "rust/remaining_compute_units",
    "rust/ro_account_modify",
    "rust/ro_modify",
    "rust/sanity",
    "rust/secp256k1_recover",
    "rust/sha",
    "rust/sibling_inner_instructions",
    "rust/sibling_instructions",
    "rust/simulation",
    "rust/spoof1",
    "rust/spoof1_system",
    "rust/sysvar",
    "rust/upgradeable",
    "rust/upgraded",
]

[patch.crates-io]
# We include the following crates as our dependencies from crates.io:
#
#  * spl-associated-token-account
#  * spl-instruction-padding
#  * spl-memo
#  * spl-pod
#  * spl-token
#  * spl-token-2022
#  * spl-token-metadata-interface
#
# They are included indirectly, for example, `account-decoder` depends on
#
#     solana-sdk = { workspace = true }
#
# and that is specified as
#
#     spl-token = "=3.5.0"
#
# in `../../Cargo.toml`.
#
# `spl-token`, in turn, depends on `solana-program`, which we explicitly specify
# above as a local path dependency:
#
#     solana-program = { path = "../../sdk/program", version = "=1.16.0" }
#
# Unfortunately, Cargo will try to resolve the `spl-token` `solana-program`
# dependency only using what is available on crates.io.  Crates.io normally
# contains a previous version of these crates, and we end up with two versions
# of `solana-program` and `solana-zk-token-sdk` and all of their dependencies in
# our build tree.
#
# If you are developing downstream using non-crates-io solana-program (local or
# forked repo, or from github rev, eg), duplicate the following patch statements
# in your Cargo.toml. If you still hit duplicate-type errors with the patch
# statements in place, run `cargo update -p solana-program` and/or `cargo update
# -p solana-zk-token-sdk` to remove extraneous versions from your Cargo.lock
# file.
#
# There is a similar override in `../../Cargo.toml`.  Please keep both comments
# and the overrides in sync.
solana-curve25519 = { path = "../../curves/curve25519" }
solana-program = { path = "../../sdk/program" }
solana-zk-token-sdk = { path = "../../zk-token-sdk" }
