[package]
name = "rbpf-cli"
description = "Decommissioned CLI to test and analyze SBF programs"
keywords = ["SBF", "interpreter", "JIT"]
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
