[package]
name = "solana-sbf-rust-rand"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
getrandom = { workspace = true, features = ["custom"] }
rand = { workspace = true }
solana-program = { workspace = true }

[lib]
crate-type = ["cdylib"]
