[store]
dir = "target/nextest"

[profile.ci]
failure-output = "immediate-final"
fail-fast = false

[profile.ci.junit]
path = "junit.xml"

[[profile.ci.overrides]]
filter = "package(solana-zk-token-proof-program-tests) & test(/^test_batched_range_proof_u256$/)"
threads-required = "num-cpus"

[[profile.ci.overrides]]
filter = "package(solana-gossip) & test(/^test_star_network_push_star_200/)"
threads-required = "num-cpus"

[[profile.ci.overrides]]
filter = "package(solana-gossip) & test(/^test_star_network_push_ring_200/)"
threads-required = "num-cpus"

[[profile.ci.overrides]]
filter = "package(solana-gossip) & test(/^cluster_info::tests::new_with_external_ip_test_random/)"
threads-required = "num-cpus"

[[profile.ci.overrides]]
filter = "package(solana-cargo-build-sbf)"
threads-required = "num-cpus"
