[package]
name = "solana-cargo-build-bpf"
description = "Compile a local package and all of its dependencies using the Solana SBF SDK"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true, features = ["std"] }
solana-logger = { workspace = true }

[features]
program = []

[[bin]]
name = "cargo-build-bpf"
path = "src/main.rs"
