name: release-artifacts-manually

on:
  workflow_dispatch:
    inputs:
      commit:
        type: string
        required: true
        description: commit

jobs:
  release-artifacts:
    uses: ./.github/workflows/release-artifacts.yml
    with:
      commit: ${{ github.event.inputs.commit }}
    secrets:
      GCS_RELEASE_BUCKET_WRITER_CREDIENTIAL: ${{ secrets.GCS_RELEASE_BUCKET_WRITER_CREDIENTIAL }}
