[package]
name = "svm-core"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = {path = "../../../solana/sdk/program", version = "=2.0.3"}
solana-sdk = { path = "../../../solana/sdk", version = "=2.0.3" }
solana-svm = {path = "../../../solana/svm", version = "=2.0.3"}
solana-program-runtime = {path = "../../../solana/program-runtime", version = "=2.0.3"}
solana-compute-budget = {path = "../../../solana/compute-budget", version = "=2.0.3"}
solana-bpf-loader-program = {path = "../../../solana/programs/bpf_loader", version = "=2.0.3"}
solana-system-program = {path = "../../../solana/programs/system", version = "=2.0.3"}
bincode = "1.3.3"

[patch.crates-io.curve25519-dalek]
git = "https://github.com/anza-xyz/curve25519-dalek.git"
rev = "b500cdc2a920cd5bff9e2dd974d7b97349d61464"

[patch.crates-io.ed25519-dalek]
git = "https://github.com/staaason/ed25519-dalek.git"
rev = "91938d89eb5ca4a141d6fda1d1db11aebadc4388"