[package]
name = "solana-sbf-rust-invoke"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
rustversion = { workspace = true }
solana-program = { workspace = true }
solana-sbf-rust-invoke-dep = { workspace = true }
solana-sbf-rust-invoked-dep = { workspace = true }
solana-sbf-rust-realloc-dep = { workspace = true }

[lib]
crate-type = ["cdylib"]
