[package]
name = "solana-cargo-test-bpf"
description = "Execute all unit and integration tests after building with the Solana SBF SDK"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "cargo-test-bpf"
path = "src/main.rs"
