[package]
name = "solana-zk-token-proof-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
bytemuck = { workspace = true }
curve25519-dalek = { workspace = true }
solana-compute-budget = { workspace = true }
solana-program-test = { workspace = true }
solana-sdk = { workspace = true }
solana-zk-token-sdk = { workspace = true }
