[package]
name = "solana-sbf-rust-upgradeable"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
solana-program = { workspace = true }

[lib]
name = "solana_sbf_rust_upgradeable"
crate-type = ["cdylib"]
